### ISSUE TITLE
File not found on loading - due to case mismatch

### ISSUE THREAD

**Issue by nickclare** [arzg/sema#1]
Hi. The `package.json` file specifies `Seema-color-theme.json`, whereas the file on disk is named `seema-color-theme.json`, so on case sensitive file systems (I'm testing on Linux / ext4), it doesn't load correctly. Renaming the file solved the issue for me temporarily

**Comment by lunacookies** [comment]
Funny you should mention that – I have an unpushed commit locally that changes exactly this. Sorry for the inconvenience, I’ll push it now :)

**Comment by lunacookies** [comment]
Fixed by 11aa0b0. I’ve released 1.4.1 so that the fix is available straight away.
