### ISSUE TITLE
Request: Please publish to open-vsx too

### ISSUE THREAD

**Issue by DarrienG** [arzg/sema#2]
OpenVsx is the default store for folks who use [VsCodium](https://github.com/VSCodium/vscodium) (VsCode but without the Microsoft bits).

It isn't too hard to publish there too: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

If it's no trouble, it would be much appreciated :)

**Comment by lunacookies** [comment]
I’m not sure if this will work; I’ll publish an empty patch version bump to see if it all goes smoothly.

**Comment by lunacookies** [comment]
I got it right eventually :)

The only thing left is to get ownership of the `arzg` namespace on the Open VSX Registry, which I’ve requested in [this issue](https://github.com/EclipseFdn/open-vsx.org/issues/470).

**Comment by DarrienG** [comment]
I appreciate it, thanks so much!
