### ISSUE TITLE
Feature request: for JetBrains IDEs

### ISSUE THREAD

**Issue by RagibHasin** [arzg/sema#4]
Thanks for this amazing theme!

It would be wonderful to be able to use it on CLion.

Thanks in advance!

**Comment by lunacookies** [comment]
Unfortunately the JetBrains IDEs do not at the moment support all the granular highlighting sema relies on. For instance, JetBrains IDEs support highlighting mutable variables and parameters throughout a function, but don’t support highlighting `&mut self` methods and items from traits.

[The core purpose of sema](https://arzg.github.io/sema/) is to emphasise these tricky parts of code and reduce other highlighting. If these elements cannot be highlighted, what is left will look very bland.

**Comment by RagibHasin** [comment]
It is really sad then. May be if JetBrains support it some day, then sema would be ported.
Thanks for your prompt response.
