### ISSUE TITLE
Q: How do i change the color of comment?

### ISSUE THREAD

**Issue by prajwalch** [arzg/sema#7]
I tried this but it didn't worked
`
"editor.tokenColorCustomizations": {
        "comments": "#474747",
    },
`

**Comment by lunacookies** [comment]
FYI the bright comments weren’t an accident; comments usually contain some sort of explanation of how a piece of code works that isn’t obvious from the code itself (that’s why the comment is there!), so it makes sense to emphasize them. This also helps avoid “comment rot”, when comments become out of date over time as the code around them evolves but people forget to update them.
